import { toolkitResult } from './results';

export type DigestAlgorithm = 'SHA-256' | 'SHA-384' | 'SHA-512';
const strengthLabels = [
  'Very guessable',
  'Guessable',
  'Some resistance',
  'Good resistance',
  'Strong resistance',
];

export async function assessPassword(password: string) {
  if (!password) throw new Error('Enter a password to assess.');
  if (password.length > 256)
    throw new Error('Use at most 256 characters for this interactive assessment.');
  const { default: zxcvbn } = await import('zxcvbn');
  const assessment = zxcvbn(password);
  const suggestions = assessment.feedback.suggestions;
  const advice = [
    ...(assessment.feedback.warning ? [assessment.feedback.warning] : []),
    ...suggestions,
  ];
  return toolkitResult(
    'password-strength',
    'Local password strength assessment',
    { assessment: 'Password strength', method: 'zxcvbn', inputIncluded: false },
    [
      { label: 'Estimated strength', value: strengthLabels[assessment.score] },
      { label: 'Score', value: assessment.score + ' / 4' },
      { label: 'Character count', value: [...password].length },
      { label: 'Processing', value: 'Local browser only' },
      { label: 'Password in this report', value: 'Excluded' },
    ],
    {
      warnings: [
        'This is a pattern-based estimate, not proof of uniqueness or resistance to a specific attack. The bundled model is primarily tuned to English-language patterns.',
      ],
      steps: [
        {
          title: 'Estimate predictable patterns',
          description:
            'zxcvbn considers common strings, repetition, sequences, and combinations rather than requiring an arbitrary character checklist.',
        },
        ...advice.map((description, index) => ({
          title: 'Suggestion ' + (index + 1),
          description,
        })),
        {
          title: 'Strengthen account protection',
          description:
            'Use a unique password generated by a password manager and enable a phishing-resistant sign-in method where available.',
        },
      ],
      sources: ['https://github.com/dropbox/zxcvbn'],
      data: { score: assessment.score, sourceIncluded: false },
    },
  );
}

export async function hashText(text: string, algorithm: DigestAlgorithm) {
  if (!['SHA-256', 'SHA-384', 'SHA-512'].includes(algorithm))
    throw new Error('Choose SHA-256, SHA-384, or SHA-512.');
  if (text.length > 100000)
    throw new Error('Hash at most 100,000 characters in this interactive tool.');
  if (!globalThis.crypto?.subtle)
    throw new Error(
      'Web Crypto is unavailable. Open SubnetIQ over HTTPS or localhost in a supported browser.',
    );
  const bytes = new TextEncoder().encode(text);
  const digest = await globalThis.crypto.subtle.digest(algorithm, bytes);
  const hex = Array.from(new Uint8Array(digest), (value) =>
    value.toString(16).padStart(2, '0'),
  ).join('');
  return toolkitResult(
    'hash',
    algorithm + ' text digest',
    { algorithm, encoding: 'UTF-8', byteLength: bytes.length, sourceIncluded: false },
    [
      { label: 'Algorithm', value: algorithm },
      { label: 'Encoding', value: 'UTF-8' },
      { label: 'Input bytes', value: bytes.length },
      { label: 'Digest bits', value: digest.byteLength * 8 },
      { label: 'Hexadecimal digest', value: hex },
      { label: 'Source text in this report', value: 'Excluded' },
    ],
    {
      warnings: [
        'SHA-2 is a fast digest, not a password-storage scheme or encryption. A digest of predictable sensitive text may be guessable.',
      ],
      steps: [
        {
          title: 'Encode exactly what was entered',
          description:
            'TextEncoder converts the input to UTF-8. Spaces, line breaks, and Unicode normalization differences affect the digest; no trimming is performed.',
        },
        {
          title: 'Compute with Web Crypto',
          description:
            'The browser computes ' +
            algorithm +
            ' locally, then formats each output byte as two hexadecimal digits.',
        },
        {
          title: 'Export the digest',
          description:
            'Only the digest, algorithm, encoding, and size metadata enter this result. The source text is excluded from copy, sharing, saved history, and AI attachments.',
        },
      ],
      sources: [
        'https://www.w3.org/TR/WebCryptoAPI/#subtlecrypto-interface',
        'https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html',
      ],
      data: { hex, algorithm, sourceIncluded: false },
    },
  );
}
