export interface RegistryEntry {
  cidr: string;
  name: string;
  category: string;
  source: boolean | null;
  destination: boolean | null;
  forwardable: boolean | null;
  globallyReachable: boolean | null;
  reservedByProtocol: boolean | null;
  reference: string;
  family: number;
  registryVersion: string;
  reviewedAt: string;
  sourceUrl: string;
  kind: string;
  notes: string;
}

export const REGISTRY_VERSION = '2025-10-09';
export const REGISTRY_REVIEWED_AT = '2026-10-04';

export const ipv4Registry: RegistryEntry[] = [
  {
    cidr: '0.0.0.0/8',
    name: 'This network',
    category: 'Current network',
    source: true,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 791',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '0.0.0.0/32',
    name: 'This host on this network',
    category: 'Unspecified',
    source: true,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 1122',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '10.0.0.0/8',
    name: 'Private-Use',
    category: 'Private RFC 1918',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 1918',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '100.64.0.0/10',
    name: 'Shared Address Space',
    category: 'Carrier-grade NAT',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 6598',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '127.0.0.0/8',
    name: 'Loopback',
    category: 'Loopback',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 1122',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'The IANA registry records limited protocol-specific exceptions; loopback is not generally forwardable.',
  },
  {
    cidr: '169.254.0.0/16',
    name: 'Link Local',
    category: 'Link-local / APIPA',
    source: true,
    destination: true,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 3927',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '172.16.0.0/12',
    name: 'Private-Use',
    category: 'Private RFC 1918',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 1918',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.0/24',
    name: 'IETF Protocol Assignments',
    category: 'Protocol assignments',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 6890',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.0/29',
    name: 'IPv4 Service Continuity Prefix',
    category: 'Service continuity',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 7335',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.8/32',
    name: 'IPv4 dummy address',
    category: 'Dummy address',
    source: true,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 7600',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.9/32',
    name: 'Port Control Protocol Anycast',
    category: 'Protocol anycast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7723',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.10/32',
    name: 'Traversal Using Relays around NAT Anycast',
    category: 'Protocol anycast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 8155',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.170/32',
    name: 'NAT64/DNS64 Discovery',
    category: 'Translation discovery',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 8880, RFC 7050',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.0.171/32',
    name: 'NAT64/DNS64 Discovery',
    category: 'Translation discovery',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 8880, RFC 7050',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.0.2.0/24',
    name: 'Documentation (TEST-NET-1)',
    category: 'Documentation',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 5737',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.31.196.0/24',
    name: 'AS112-v4',
    category: 'AS112 service',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7535',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.52.193.0/24',
    name: 'AMT',
    category: 'Multicast tunneling',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7450',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.88.99.0/24',
    name: 'Deprecated (6to4 Relay Anycast)',
    category: 'Deprecated transition',
    source: null,
    destination: null,
    forwardable: null,
    globallyReachable: null,
    reservedByProtocol: null,
    reference: 'RFC 7526',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Registration terminated; historical classification only. Registry reachability flags are unspecified.',
  },
  {
    cidr: '192.88.99.2/32',
    name: '6a44-relay anycast address',
    category: '6a44 relay anycast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 6751',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.168.0.0/16',
    name: 'Private-Use',
    category: 'Private RFC 1918',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 1918',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '192.175.48.0/24',
    name: 'Direct Delegation AS112 Service',
    category: 'AS112 service',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7534',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '198.18.0.0/15',
    name: 'Benchmarking',
    category: 'Benchmarking',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 2544',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '198.51.100.0/24',
    name: 'Documentation (TEST-NET-2)',
    category: 'Documentation',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 5737',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '203.0.113.0/24',
    name: 'Documentation (TEST-NET-3)',
    category: 'Documentation',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 5737',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '224.0.0.0/4',
    name: 'IPv4 Multicast',
    category: 'Multicast',
    source: false,
    destination: true,
    forwardable: null,
    globallyReachable: null,
    reservedByProtocol: true,
    reference: 'RFC 5771',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc5771.html',
    kind: 'architectural',
    notes:
      'Architectural classification supplements the special-purpose registry. Routing and assignment require separate verification.',
  },
  {
    cidr: '224.0.0.0/24',
    name: 'Local Network Control Block',
    category: 'Link-local multicast',
    source: false,
    destination: true,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 5771',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc5771.html',
    kind: 'architectural',
    notes:
      'Architectural classification supplements the special-purpose registry. Routing and assignment require separate verification.',
  },
  {
    cidr: '239.0.0.0/8',
    name: 'Administratively Scoped Multicast',
    category: 'Administrative multicast',
    source: false,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 2365',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc2365.html',
    kind: 'architectural',
    notes:
      'Architectural classification supplements the special-purpose registry. Routing and assignment require separate verification.',
  },
  {
    cidr: '240.0.0.0/4',
    name: 'Reserved',
    category: 'Reserved',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 1112',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '255.255.255.255/32',
    name: 'Limited Broadcast',
    category: 'Limited broadcast',
    source: false,
    destination: true,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 8190, RFC 919',
    family: 4,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
];

export const ipv6Registry: RegistryEntry[] = [
  {
    cidr: '::1/128',
    name: 'Loopback Address',
    category: 'Loopback',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 4291',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '::/128',
    name: 'Unspecified Address',
    category: 'Unspecified',
    source: true,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 4291',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '::ffff:0:0/96',
    name: 'IPv4-mapped Address',
    category: 'IPv4-mapped',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 4291',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '64:ff9b::/96',
    name: 'IPv4-IPv6 Translation',
    category: 'NAT64 well-known prefix',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 6052',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '64:ff9b:1::/48',
    name: 'IPv4-IPv6 Translation',
    category: 'Local-use translation',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 8215',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '100::/64',
    name: 'Discard-Only Address Block',
    category: 'Discard-only',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 6666',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '100:0:0:1::/64',
    name: 'Dummy IPv6 Prefix',
    category: 'Dummy address',
    source: true,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 9780',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2000::/3',
    name: 'IPv6 Global Unicast',
    category: 'Global unicast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 4291',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc4291.html',
    kind: 'architectural',
    notes:
      'Architectural classification supplements the special-purpose registry. Routing and assignment require separate verification.',
  },
  {
    cidr: '2001::/23',
    name: 'IETF Protocol Assignments',
    category: 'Protocol assignments',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 2928',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001::/32',
    name: 'TEREDO',
    category: 'Teredo transition',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: null,
    reservedByProtocol: false,
    reference: 'RFC 4380, RFC 8190',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Global reachability is context-dependent in the IANA registry; consult the referenced transition specification.',
  },
  {
    cidr: '2001:1::1/128',
    name: 'Port Control Protocol Anycast',
    category: 'Protocol anycast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7723',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:1::2/128',
    name: 'Traversal Using Relays around NAT Anycast',
    category: 'Protocol anycast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 8155',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:1::3/128',
    name: 'DNS-SD Service Registration Protocol Anycast',
    category: 'Protocol anycast',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 9665',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:2::/48',
    name: 'Benchmarking',
    category: 'Benchmarking',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 5180',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:3::/32',
    name: 'AMT',
    category: 'Multicast tunneling',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7450',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:4:112::/48',
    name: 'AS112-v6',
    category: 'AS112 service',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7535',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:10::/28',
    name: 'Deprecated (previously ORCHID)',
    category: 'Deprecated ORCHID',
    source: null,
    destination: null,
    forwardable: null,
    globallyReachable: null,
    reservedByProtocol: null,
    reference: 'RFC 4843',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Registration terminated; historical classification only. Registry reachability flags are unspecified.',
  },
  {
    cidr: '2001:20::/28',
    name: 'ORCHIDv2',
    category: 'ORCHIDv2',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7343',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:30::/28',
    name: 'Drone Remote ID Protocol Entity Tags (DETs) Prefix',
    category: 'Drone identity',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 9374',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2001:db8::/32',
    name: 'Documentation',
    category: 'Documentation',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 3849',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '2002::/16',
    name: '6to4',
    category: 'Historical 6to4',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: null,
    reservedByProtocol: false,
    reference: 'RFC 3056',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Global reachability is context-dependent in the IANA registry; consult the referenced transition specification.',
  },
  {
    cidr: '2620:4f:8000::/48',
    name: 'Direct Delegation AS112 Service',
    category: 'AS112 service',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: true,
    reservedByProtocol: false,
    reference: 'RFC 7534',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '3fff::/20',
    name: 'Documentation',
    category: 'Documentation',
    source: false,
    destination: false,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 9637',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: '5f00::/16',
    name: 'Segment Routing (SRv6) SIDs',
    category: 'Segment routing',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 9602',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: 'fc00::/7',
    name: 'Unique-Local',
    category: 'Unique local',
    source: true,
    destination: true,
    forwardable: true,
    globallyReachable: false,
    reservedByProtocol: false,
    reference: 'RFC 4193, RFC 8190',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: 'fe80::/10',
    name: 'Link-Local Unicast',
    category: 'Link-local',
    source: true,
    destination: true,
    forwardable: false,
    globallyReachable: false,
    reservedByProtocol: true,
    reference: 'RFC 4291',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl:
      'https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml',
    kind: 'registry',
    notes:
      'Flags are descriptive registry data and do not guarantee routing, assignment, or successful connectivity.',
  },
  {
    cidr: 'ff00::/8',
    name: 'IPv6 Multicast',
    category: 'Multicast',
    source: false,
    destination: true,
    forwardable: null,
    globallyReachable: null,
    reservedByProtocol: true,
    reference: 'RFC 4291',
    family: 6,
    registryVersion: '2025-10-09',
    reviewedAt: '2026-10-04',
    sourceUrl: 'https://www.rfc-editor.org/rfc/rfc4291.html',
    kind: 'architectural',
    notes:
      'Architectural classification supplements the special-purpose registry. Routing and assignment require separate verification.',
  },
];
